# Generated by Django 3.0.7 on 2020-07-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoimpression',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
        ),
    ]
