# Generated by Django 3.0.7 on 2020-06-29 11:57

import Main.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.TextField(default=Main.utils.generetePlaylistId, editable=False, max_length=35, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(to='Main.Video')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('creator', 'title'), name='unique_playlist_per_user'),
        ),
    ]
