# Generated by Django 3.0.7 on 2020-06-29 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoImpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Video')),
            ],
        ),
        migrations.AddConstraint(
            model_name='videoimpression',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='one_impression_foreach_user_on_a_video'),
        ),
    ]
