# Generated by Django 3.0.7 on 2020-07-08 20:30

import Main.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.TextField(default=Main.utils.generateChannelId, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, max_length=1500, null=True)),
                ('profil_img', models.ImageField(default='images/users/default.png', upload_to=Main.utils.randomFileName)),
                ('profil_background', models.ImageField(default='images/users/default_background.jpeg', upload_to=Main.utils.randomFileName)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
