# Generated by Django 3.0.7 on 2020-07-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='User',
            new_name='user',
        ),
    ]
