# Generated by Django 3.0.7 on 2020-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20200708_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='profil_background',
            field=models.TextField(default='/media/images/users/default_background.jpeg'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='profil_img',
            field=models.TextField(default='/media/images/users/default.png'),
        ),
    ]
