# Generated by Django 3.0.7 on 2020-07-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200710_1245'),
        ('channel', '0003_auto_20200711_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='favorite_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_video', to='Main.Video'),
        ),
    ]
